"use client";

import { useState } from "react";
import { dateTime } from "@/lib/format";
import type { Decision, InsightAction, InsightRow } from "@/lib/types";
import { Badge, Button, cx, inputClass } from "../ui";
import { Panel } from "./panels";

// Generate Insights: asks the server for a recommendation based on the
// aggregated metrics of the dataset being viewed, then lets the campaign owner
// accept or reject each suggested action. Nothing is applied automatically.

function ActionCard({
  insightId,
  index,
  action,
  onSaved,
}: {
  insightId: string;
  index: number;
  action: InsightAction;
  onSaved: (actions: InsightAction[]) => void;
}) {
  const [note, setNote] = useState(action.note);
  const [saving, setSaving] = useState<Decision | null>(null);
  const [error, setError] = useState<string | null>(null);

  async function decide(decision: Decision) {
    setError(null);
    setSaving(decision);
    try {
      const response = await fetch(`/api/admin/insights/${insightId}`, {
        method: "PATCH",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ index, decision, note: decision === "pending" ? "" : note }),
      });
      const data = await response.json().catch(() => null);
      if (response.ok && data) {
        if (decision === "pending") setNote("");
        onSaved(data.next_actions);
      } else {
        setError(data?.message ?? "Could not save your decision.");
      }
    } catch {
      setError("Could not reach the server.");
    }
    setSaving(null);
  }

  const decided = action.decision !== "pending";

  return (
    <li
      className={cx(
        "rounded-xl border p-4",
        action.decision === "accepted" && "border-good/30 bg-good-soft",
        action.decision === "rejected" && "border-line bg-paper",
        !decided && "border-line bg-card",
      )}
    >
      <div className="flex flex-wrap items-start justify-between gap-2">
        <p className="max-w-prose font-medium text-ink">{action.action}</p>
        {action.decision === "accepted" && <Badge tone="good">Accepted</Badge>}
        {action.decision === "rejected" && <Badge>Rejected</Badge>}
      </div>
      <p className="mt-1.5 max-w-prose text-sm text-body">{action.why}</p>
      <p className="mt-2 text-xs text-muted">
        Should move: <span className="font-medium text-ink">{action.metric}</span>
      </p>

      {decided ? (
        <div className="mt-3 flex flex-wrap items-center gap-3 border-t border-line/70 pt-3 text-sm">
          <p className="flex-1 text-body">
            <span className="text-muted">Your reason: </span>
            {action.note || <span className="text-muted">none recorded</span>}
          </p>
          <Button variant="ghost" className="px-0 py-0" loading={saving === "pending"} onClick={() => decide("pending")}>
            Change decision
          </Button>
        </div>
      ) : (
        <div className="mt-3 flex flex-col gap-2 border-t border-line pt-3 sm:flex-row">
          <input
            aria-label="Reason for your decision"
            placeholder="Why? (recorded with your decision)"
            maxLength={300}
            className={inputClass}
            value={note}
            onChange={(e) => setNote(e.target.value)}
          />
          <div className="flex shrink-0 gap-2">
            <Button variant="dark" loading={saving === "accepted"} disabled={saving !== null} onClick={() => decide("accepted")}>
              Accept
            </Button>
            <Button variant="secondary" loading={saving === "rejected"} disabled={saving !== null} onClick={() => decide("rejected")}>
              Reject
            </Button>
          </div>
        </div>
      )}
      {error && (
        <p role="alert" className="mt-2 text-sm text-accent-dark">
          {error}
        </p>
      )}
    </li>
  );
}

function Insight({ insight, onChange }: { insight: InsightRow; onChange: (row: InsightRow) => void }) {
  return (
    <div>
      <div className="flex flex-wrap items-center gap-2 text-xs text-muted">
        <Badge tone={insight.generated_by === "ai" ? "accent" : "neutral"}>
          {insight.generated_by === "ai" ? "Generated by AI" : "Rule-based fallback"}
        </Badge>
        {insight.is_demo && <Badge tone="warn">Based on DEMO DATA</Badge>}
        <span>{dateTime(insight.created_at)}</span>
      </div>

      <div className="mt-4 grid gap-3 md:grid-cols-2">
        <div className="rounded-xl border border-line bg-paper p-4">
          <p className="text-xs font-semibold uppercase tracking-wider text-good">Working</p>
          <p className="mt-1.5 font-semibold text-ink">{insight.working.headline}</p>
          <p className="mt-1 text-sm leading-relaxed text-body">{insight.working.detail}</p>
        </div>
        <div className="rounded-xl border border-line bg-paper p-4">
          <p className="text-xs font-semibold uppercase tracking-wider text-accent-dark">Leaking</p>
          <p className="mt-1.5 font-semibold text-ink">{insight.leaking.headline}</p>
          <p className="mt-1 text-sm leading-relaxed text-body">{insight.leaking.detail}</p>
        </div>
      </div>

      <p className="mt-5 text-xs font-semibold uppercase tracking-wider text-muted">Next 24 hours</p>
      <p className="mt-1 text-sm text-muted">Recommendations only. Nothing changes until you decide.</p>
      <ul className="mt-3 space-y-3">
        {insight.next_actions.map((action, index) => (
          <ActionCard
            key={`${insight.id}-${index}-${action.decision}`}
            insightId={insight.id}
            index={index}
            action={action}
            onSaved={(next_actions) => onChange({ ...insight, next_actions })}
          />
        ))}
      </ul>
    </div>
  );
}

export function InsightsPanel({
  dataset,
  initial,
  aiConfigured,
}: {
  dataset: "real" | "demo";
  initial: InsightRow[];
  aiConfigured: boolean;
}) {
  const [insights, setInsights] = useState(initial);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);

  async function generate() {
    setError(null);
    setLoading(true);
    try {
      const response = await fetch("/api/admin/insights", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ dataset }),
      });
      const data = await response.json().catch(() => null);
      if (response.ok && data?.insight) setInsights([data.insight, ...insights]);
      else setError(data?.message ?? "Could not generate insights. Please try again.");
    } catch {
      setError("Could not reach the server.");
    }
    setLoading(false);
  }

  const update = (row: InsightRow) => setInsights(insights.map((i) => (i.id === row.id ? row : i)));
  const [latest, ...earlier] = insights;

  return (
    <Panel
      title="Growth insights"
      hint={
        aiConfigured
          ? "Aggregated metrics are sent to the AI model. No names, emails or other personal data leave the database."
          : "No AI key configured: insights come from the built-in rule-based analysis of the same aggregated metrics."
      }
      action={
        <Button onClick={generate} loading={loading}>
          {loading ? "Analysing…" : "Generate Insights"}
        </Button>
      }
    >
      {error && (
        <p role="alert" className="mb-4 rounded-lg border border-accent/25 bg-accent-soft px-3.5 py-3 text-sm text-ink">
          {error}
        </p>
      )}
      {!latest ? (
        <p className="rounded-lg border border-dashed border-line px-4 py-8 text-center text-sm text-muted">
          No insights yet for this dataset. Click Generate Insights to analyse the current funnel.
        </p>
      ) : (
        <>
          <Insight insight={latest} onChange={update} />
          {earlier.length > 0 && (
            <details className="mt-6 border-t border-line pt-4">
              <summary className="cursor-pointer text-sm font-medium text-muted hover:text-ink">
                Earlier insights ({earlier.length})
              </summary>
              <div className="mt-4 space-y-8">
                {earlier.map((insight) => (
                  <Insight key={insight.id} insight={insight} onChange={update} />
                ))}
              </div>
            </details>
          )}
        </>
      )}
    </Panel>
  );
}
